import { useEffect, useState } from "react";
import { Boxes, FileImage, LayoutDashboard, LogOut, Package, Plus, ReceiptText, Search, ShieldCheck } from "lucide-react";
import { isConfigured, supabase } from "./supabase.js";

const nav = [["overview", "Overview", LayoutDashboard], ["products", "Products", Package], ["assets", "Digital Assets", FileImage], ["inventory", "Inventory", Boxes], ["orders", "Orders", ReceiptText]];
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState("");
  async function submit(event) {
    event.preventDefault();
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    setNotice(error ? error.message : "Signed in successfully.");
  }
  return <main className="login"><section><p className="eyebrow">NEXUS / COMMERCE OPERATIONS</p><h1>One operational view for every product decision.</h1><p className="lead">A PIM, DAM and inventory workspace built to move product teams from scattered data to confident execution.</p><div className="login-points"><span><ShieldCheck /> Supabase Auth</span><span><Boxes /> Inventory ledger</span><span><FileImage /> Asset workflow</span></div></section><form onSubmit={submit} className="auth-card"><p className="eyebrow">WORKSPACE ACCESS</p><h2>Welcome back</h2><label>Work email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required placeholder="you@company.com" /></label><label>Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required /></label><button>Sign in <span>→</span></button>{notice && <p className="notice">{notice}</p>}</form></main>;
}

function App() {
  const [session, setSession] = useState(null);
  const [active, setActive] = useState("overview");
  const [data, setData] = useState({ products: [], categories: [], assets: [], movements: [], orders: [] });
  const [loading, setLoading] = useState(true);
  useEffect(() => { if (!isConfigured) return; supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: listener } = supabase.auth.onAuthStateChange((_, next) => setSession(next)); return () => listener.subscription.unsubscribe(); }, []);
  async function load() {
    setLoading(true);
    const [products, inventory, categories, assets, movements, orders] = await Promise.all([
      supabase.from("products").select("*, categories(name)").order("created_at", { ascending: false }),
      supabase.from("product_inventory").select("product_id, quantity_on_hand"),
      supabase.from("categories").select("*").order("name"),
      supabase.from("digital_assets").select("*, products(name, sku)").order("created_at", { ascending: false }),
      supabase.from("inventory_movements").select("*, products(name, sku)").order("created_at", { ascending: false }).limit(25),
      supabase.from("orders").select("*").order("ordered_at", { ascending: false })
    ]);
    const stockByProduct = new Map((inventory.data ?? []).map((item) => [item.product_id, item.quantity_on_hand]));
    setData({ products: (products.data ?? []).map((product) => ({ ...product, quantity_on_hand: stockByProduct.get(product.id) ?? 0 })), categories: categories.data ?? [], assets: assets.data ?? [], movements: movements.data ?? [], orders: orders.data ?? [] }); setLoading(false);
  }
  useEffect(() => { if (session) load(); }, [session]);
  if (!isConfigured) return <main className="setup"><p className="eyebrow">CONFIGURATION REQUIRED</p><h1>Connect your Supabase project.</h1><p>Create `.env` from `.env.example`, then add `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY`.</p></main>;
  if (!session) return <Login />;
  const title = nav.find(([key]) => key === active)[1];
  return <div className="shell"><aside><div className="brand"><span>N</span><div>NEXUS<small>COMMERCE OPERATIONS</small></div></div><nav>{nav.map(([key, label, Icon]) => <button key={key} className={active === key ? "active" : ""} onClick={() => setActive(key)}><Icon />{label}</button>)}</nav><div className="account"><div className="avatar">{session.user.email[0].toUpperCase()}</div><div><strong>{session.user.email.split("@")[0]}</strong><small>Operations Admin</small></div><button aria-label="Sign out" onClick={() => supabase.auth.signOut()}><LogOut /></button></div></aside><main className="workspace"><header><div><p className="eyebrow">OPERATIONS / {title.toUpperCase()}</p><h1>{title}</h1></div>{active !== "overview" && <button className="primary" onClick={() => document.getElementById("create-dialog").showModal()}><Plus /> New {active.slice(0, -1)}</button>}</header>{loading ? <div className="loading">Loading operational data...</div> : <Module active={active} data={data} reload={load} />}</main></div>;
}

function Module({ active, data, reload }) { if (active === "overview") return <Overview data={data} />; if (active === "products") return <Products data={data} reload={reload} />; if (active === "assets") return <Assets data={data} reload={reload} />; if (active === "inventory") return <Inventory data={data} reload={reload} />; return <Orders data={data} reload={reload} />; }
function Overview({ data }) { const sales = data.orders.filter((o) => o.status !== "cancelled").reduce((sum, o) => sum + Number(o.total), 0); const low = data.products.filter((p) => p.quantity_on_hand <= p.reorder_point); return <><section className="metrics"><Metric label="Active products" value={data.products.filter((p) => p.status === "active").length} note={`${data.products.length} catalog records`} /><Metric label="Inventory value" value={money.format(data.products.reduce((sum, p) => sum + Number(p.cost) * p.quantity_on_hand, 0))} note="At landed cost" /><Metric label="Sales pipeline" value={money.format(sales)} note={`${data.orders.length} tracked orders`} /><Metric label="Assets approved" value={`${data.assets.filter((a) => a.status === "approved").length}/${data.assets.length}`} note="Ready for publishing" /></section><section className="split"><Panel title="Low stock attention" action="Inventory"><table><thead><tr><th>Product</th><th>On hand</th><th>Reorder point</th></tr></thead><tbody>{low.length ? low.map((p) => <tr key={p.id}><td><strong>{p.name}</strong><small>{p.sku}</small></td><td className="danger">{p.quantity_on_hand}</td><td>{p.reorder_point}</td></tr>) : <Empty label="All products are above their reorder point." />}</tbody></table></Panel><Panel title="Recent orders" action="Orders"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{data.orders.slice(0, 5).map((o) => <tr key={o.id}><td><strong>{o.order_number}</strong></td><td>{o.customer_name}</td><td>{money.format(o.total)}</td><td><Status value={o.status} /></td></tr>)}</tbody></table></Panel></section></> }
function Metric({ label, value, note }) { return <article className="metric"><p>{label}</p><h2>{value}</h2><small>{note}</small></article> }
function Panel({ title, action, children }) { return <section className="panel"><div className="panel-head"><h2>{title}</h2><button>{action} <span>→</span></button></div>{children}</section> }
function Status({ value }) { return <span className={`status ${value}`}>{value}</span> }
function Empty({ label }) { return <tr><td colSpan="5" className="empty">{label}</td></tr> }
function Products({ data, reload }) { const [query, setQuery] = useState(""); const rows = data.products.filter((p) => `${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())); return <><Toolbar query={query} setQuery={setQuery} label="Search products" /><section className="panel"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>On hand</th><th>Publishing</th></tr></thead><tbody>{rows.map((p) => <tr key={p.id}><td><strong>{p.name}</strong><small>{p.sku}</small></td><td>{p.categories?.name ?? "Uncategorized"}</td><td>{money.format(p.price)}</td><td>{p.quantity_on_hand}</td><td><Status value={p.status} /></td></tr>)}</tbody></table></section><CreateProduct categories={data.categories} reload={reload} /></> }
function Toolbar({ query, setQuery, label }) { return <div className="toolbar"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={label} /></div> }
function CreateProduct({ categories, reload }) { async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const { error } = await supabase.from("products").insert({ sku: form.get("sku"), name: form.get("name"), category_id: form.get("category") || null, price: form.get("price"), cost: form.get("cost"), reorder_point: form.get("reorder") || 10, status: "draft" }); if (!error) { event.currentTarget.closest("dialog").close(); event.currentTarget.reset(); reload(); } } return <dialog id="create-dialog"><form method="dialog" className="dialog-head"><h2>New product</h2><button>×</button></form><form onSubmit={submit} className="form-grid"><label>Product name<input name="name" required /></label><label>SKU<input name="sku" required /></label><label>Category<select name="category"><option value="">Uncategorized</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Sale price<input name="price" type="number" min="0" step="0.01" required /></label><label>Unit cost<input name="cost" type="number" min="0" step="0.01" required /></label><label>Reorder point<input name="reorder" type="number" min="0" /></label><button className="primary">Create product</button></form></dialog> }
function Assets({ data, reload }) { return <><section className="asset-grid">{data.assets.map((a) => <article className="asset"><div className="asset-preview"><FileImage /></div><p><Status value={a.status} /></p><h3>{a.name}</h3><small>{a.products?.name ?? "Unassigned product"}</small></article>)}{!data.assets.length && <div className="empty-card">No assets yet. Upload your first product asset.</div>}</section><CreateAsset products={data.products} reload={reload} /></> }
function CreateAsset({ products, reload }) { async function submit(e) { e.preventDefault(); const form = new FormData(e.currentTarget); const file = form.get("file"); const path = `${crypto.randomUUID()}-${file.name}`; const upload = await supabase.storage.from("product-assets").upload(path, file); if (upload.error) return; const { error } = await supabase.from("digital_assets").insert({ product_id: form.get("product") || null, name: file.name, storage_path: path, mime_type: file.type, status: "draft" }); if (!error) { e.currentTarget.closest("dialog").close(); reload(); } } return <dialog id="create-dialog"><form method="dialog" className="dialog-head"><h2>Upload asset</h2><button>×</button></form><form onSubmit={submit} className="form-grid"><label>Product<select name="product"><option value="">Unassigned</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>File<input name="file" type="file" required /></label><button className="primary">Upload asset</button></form></dialog> }
function Inventory({ data, reload }) { return <><section className="panel"><table><thead><tr><th>Timestamp</th><th>Product</th><th>Movement</th><th>Quantity</th><th>Reference</th></tr></thead><tbody>{data.movements.map((m) => <tr key={m.id}><td>{new Date(m.created_at).toLocaleDateString()}</td><td><strong>{m.products?.name}</strong><small>{m.products?.sku}</small></td><td><Status value={m.movement_type} /></td><td className={m.quantity < 0 ? "danger" : "positive"}>{m.quantity > 0 ? "+" : ""}{m.quantity}</td><td>{m.reference ?? "-"}</td></tr>)}</tbody></table></section><CreateMovement products={data.products} reload={reload} /></> }
function CreateMovement({ products, reload }) { async function submit(e) { e.preventDefault(); const f = new FormData(e.currentTarget); const type = f.get("type"); const quantity = Number(f.get("quantity")) * (type === "sale" ? -1 : 1); const { error } = await supabase.from("inventory_movements").insert({ product_id: f.get("product"), movement_type: type, quantity, reference: f.get("reference") }); if (!error) { e.currentTarget.closest("dialog").close(); reload(); } } return <dialog id="create-dialog"><form method="dialog" className="dialog-head"><h2>Inventory movement</h2><button>×</button></form><form onSubmit={submit} className="form-grid"><label>Product<select name="product" required>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Movement<select name="type"><option value="receipt">Receipt</option><option value="sale">Sale</option><option value="adjustment">Adjustment</option></select></label><label>Quantity<input name="quantity" type="number" min="1" required /></label><label>Reference<input name="reference" placeholder="PO-1042" /></label><button className="primary">Record movement</button></form></dialog> }
function Orders({ data, reload }) { return <><section className="panel"><table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>{data.orders.map((o) => <tr key={o.id}><td><strong>{o.order_number}</strong></td><td>{o.customer_name}</td><td>{o.ordered_at}</td><td>{money.format(o.total)}</td><td><Status value={o.status} /></td></tr>)}</tbody></table></section><CreateOrder reload={reload} /></> }
function CreateOrder({ reload }) { async function submit(e) { e.preventDefault(); const f = new FormData(e.currentTarget); const { error } = await supabase.from("orders").insert({ order_number: f.get("number"), customer_name: f.get("customer"), total: f.get("total"), status: "confirmed", ordered_at: f.get("date") }); if (!error) { e.currentTarget.closest("dialog").close(); reload(); } } return <dialog id="create-dialog"><form method="dialog" className="dialog-head"><h2>New order</h2><button>×</button></form><form onSubmit={submit} className="form-grid"><label>Order number<input name="number" required placeholder="SO-1001" /></label><label>Customer<input name="customer" required /></label><label>Order date<input name="date" type="date" required /></label><label>Total<input name="total" type="number" min="0" step="0.01" required /></label><button className="primary">Create order</button></form></dialog> }
export default App;
